print("       * ")
print("    *    *")
print("  *    *    *")
print("*   *     *    *")
print("*  *   *   *   *")
print("*  *   *   *   *")
print("*  *   *   *   *")
print("*  *   *   *   *")
print("*  *   *   *   *")
print("This is star pattern")